# Generated by Django 6.0 on 2025-12-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_container_name_alter_drinkcategory_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="size",
            name="unique_container_volume",
        ),
        migrations.AddConstraint(
            model_name="size",
            constraint=models.UniqueConstraint(
                fields=("container", "volume_value"), name="unique_container_volume"
            ),
        ),
    ]
