# Generated by Django 6.0 on 2025-12-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpackaging",
            name="type",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="packaging",
            name="type",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
